### ISSUE TITLE
no signing certificate "Developer ID Application" found

### ISSUE THREAD

**Issue by Iamthegeekdavid** [kode54/Cog#12]
![unnamed](https://user-images.githubusercontent.com/24899439/41939348-1e5366be-795b-11e8-8202-ede4da361aee.jpg)

I wonder if I have to have an Apple Developer ID to build Cog locally.
Interestingly, without Apple Developer ID, CogAudio was built successfully as a separately project.
Thanks,

David

**Comment by kode54** [comment]
The build scripts are geared towards my own build process, for binary distribution. You're welcome to fork an unsigned repository if you wish, but I won't accept the changes upstream for any of the project files, or at least any changes pertaining to code signing.

**Comment by Iamthegeekdavid** [comment]
@kode54 ,

Thank you for your reply. I forked Cog and am not sure if it is an unsigned repo after forking. I still have the "no signing certificate" error in Xcode when I git clone it from my repo and then build it in Xcode.

Before I got to the point of "no signing certificate" problem,  there was another error shown below. I just commented out that line of code and this error was gone. I wonder if it is good to comment out it.

Thanks again!
David
<img width="1280" alt="screen shot 2018-06-27 at 8 22 46 am" src="https://user-images.githubusercontent.com/24899439/41998975-bb7965ee-7a21-11e8-8bf5-09e74822d234.png">

**Comment by kode54** [comment]
Several of the projects call for signatures, and there's a custom build step on the main project that attempts to recursively re-sign the output. You'll need to disable those if you don't have a developer certificate of your own.

Also, if you want to supply your own updates, you'll need to replace the DSA key used for signing updates and deltas, and sign bundle your own public key. Sparkle doesn't really like unsigned updates.

**Comment by Iamthegeekdavid** [comment]
Thanks for the new information on this issue.
