### ISSUE TITLE
Cog doesn't play tracks with hash # symbol in the file name.

### ISSUE THREAD

**Issue by articobandurini** [kode54/Cog#19]
If the track linked throught a .cue file it doesn't play either.

**Comment by articobandurini** [comment]
> can you provide an example bunch of filenames that don't work, @articobandurini

i have already renamed my files in ordaer to play them :) but it is easy to try renaming yourself - simply put # into the file or folder name.

**Comment by megadr01d** [comment]
@articobandurini Please close the issue if fixed.

**Comment by articobandurini** [comment]
fixed
