### ISSUE TITLE
DSF Broken

### ISSUE THREAD

**Issue by Sappharad** [kode54/Cog#24]
Dreamcast DSF playback is broken.
When you add a .dsf file in the current release, nothing happens - the files don't appear in the playlist. But adding .miniDsf containers still load fine and DSF playback works correctly for those.

Is there a conflict with another file format using the same extension?

**Comment by kode54** [comment]
It’s probably conflicting with the FFmpeg plugin. I’ll try dropping its priority while I also update other libraries, soon.

**Comment by kode54** [comment]
Please verify this issue.

**Comment by Sappharad** [comment]
Yes, you fixed it. Thanks.
