### ISSUE TITLE
Add aacPlus audio file support

### ISSUE THREAD

**Issue by megadr01d** [kode54/Cog#25]
I was under the impression that Cog supported the AAC format. I have a couple of radio stations that fail to play and I thought the issue was because they're SHOUTcast streams but, upon further investigation, I realized they were all AAC streams. SHOUTcast MP3s play fine.

**Comment by megadr01d** [comment]
My bad. They're actually aacPlus streams.

Examples to open in the browser (remove the "listen.pls" string to see the SHOUTcast info):

http://79.120.77.11:9043/listen.pls
http://79.120.39.202:9125/listen.pls
http://79.120.77.11:9103/listen.pls

**Comment by kode54** [comment]
I don't think "raw" ADTS AAC is supported at all at the moment.

**Comment by megadr01d** [comment]
Yeah, and maybe it's not worth it either. It's just those 3 streams anyway.
