### ISSUE TITLE
Shuffle albums

### ISSUE THREAD

**Issue by megadr01d** [kode54/Cog#29]
Does anyone know how "Shuffle Albums" is supposed to work?

I was under the impression that if I loaded, let's say, 4 albums into the playlist and then activated "Shuffle Albums", it would play, for example, album 1, album 4, album 3, album 2, but with the songs in the right album order.

Right now, I don't see any difference between shuffling albums and shuffling tracks.

**Comment by megadr01d** [comment]
@kode54 Thanks for the [implementation](https://github.com/kode54/Cog/commit/c8f91c5092e63c006d66dd1e58c387171f1e55d3). The shuffle part works, however, it doesn't get properly activated.

If "Shuffle Albums" is **disabled** when Cog is launched with a couple of albums loaded into the playlist, and we activate the option, it skips to a random album right after the first album song finishes, instead of completing the album.

If "Shuffle Albums" is **already enabled** when Cog is launched with a couple of albums loaded into the playlist, the shuffle doesn't get activated at all and it just plays the albums in order. However, within the same session, if we deactivate a reactivate the option, the shuffle works as intended.

**Comment by megadr01d** [comment]
To test it, just use the "Next Track" shortcut key, instead of having to wait for full song playback.

**Comment by kode54** [comment]
This is already known. It doesn't even build the shuffle playlist until you activate shuffle, and it doesn't consider any tracks that were already queued or playing when creating the shuffle playlist. Otherwise, it would need to manually exclude the current album and add it first. I'll look into that later.

**Comment by megadr01d** [comment]
It seems that with the latest version all the commits regarding this got reverted. Shuffle albums is no longer working.

**Comment by kode54** [comment]
Sorry about that, I had to fix it for real this time. It was by sheer luck that it even worked at all the first time.

**Comment by megadr01d** [comment]
> If "Shuffle Albums" is already enabled when Cog is launched with a couple of albums loaded into the playlist, the shuffle doesn't get activated at all and it just plays the albums in order. However, within the same session, if we deactivate and reactivate the option, the shuffle works as intended.

Just for peace of mind, is there a way for Cog to detect if Shuffle Albums is already enabled on launch (like it does for Shuffle Tracks) and enforce the shuffling after all metadata is retrieved?
If not, I'll just close this and manually toggle it each time.

**Comment by kode54** [comment]
All metadata is supposed to be retrieved when you add the files, and is cached on disk until the files are removed from the playlist.

**Comment by megadr01d** [comment]
Yes, but "Shuffle Albums" only works **if activated manually after all metadata has populated the playlist** (we have to wait before activating the option). Enabling the shuffle **manually before all metadata has been retrieved** or **quitting Cog with the Shuffle enabled and reopening some files** won't activate the shuffle.

That was my question really, because it differs from the shuffle tracks option. I haven't tried but I assume the repeat options are also applied if already enabled on launch,

**Comment by megadr01d** [comment]
Anyway, I'll toggle the option each time i need it. If you feel it could be improved, I know it will come up on a future update. Thanks again and cheers.

**Comment by kode54** [comment]
Sorry it doesn't work as expected. It also doesn't work that well when the playlist has been modified after it is generated. I didn't design the original shuffle thing.

**Comment by megadr01d** [comment]
It's quite improved as it is and thanks for that. The original version didn't even have the album shuffle implemented at all which you tackled quite nicely.

**Comment by kode54** [comment]
And as a bare minimum of making it work, I also designed it so that when you start any album manually, it pushes it to the top of the shuffle queue, so that it will play out that album first before beginning whatever else is in the queue.
