### ISSUE TITLE
Dropping support for OS X 10.11 El Capitan?

### ISSUE THREAD

**Issue by megadr01d** [kode54/Cog#32]
Updated to latest version k54-1188-g09777d455 and...

/private/tmp/screenshot.png

**Comment by megadr01d** [comment]
Fuck GitHub, also dropping support for El Capitan's version of Safari, can't post screenshots or edit posts.

Latest version errors on launch with the following message:

> Cog cannot be opened because of a problem.
>
> Check with the developer to make sure Cog works with this version of OS X. You may need to reinstall the application. Be sure to install any available updates for the application and OS X.
>
> Click Report to see more detailed information and send a report to Apple.

**Comment by kode54** [comment]
Sorry about that, I was sloppy with my implementation of new features that require 10.12.1. They should now be selectively unused on anything older than that, allowing the older Media Key functionality to work as it originally did. Please download the latest release from my site manually.

**Comment by megadr01d** [comment]
Thanks a lot for the explanation, man. Glad you keep supporting old systems as long as possible.
Downloaded the latest, all fixed. Cheers.
