### ISSUE TITLE
Not checking for updates automatically anymore

### ISSUE THREAD

**Issue by megadr01d** [kode54/Cog#41]
Just realized Cog k54-1203-g485b81fe0 is not checking for updates on startup anymore.

**Comment by kode54** [comment]
Not only that, but it's finding somehow that it's already running the current version. And the only thing I can think of is that something happened to the Sparkle framework.

**Comment by megadr01d** [comment]
Wait, if I check for updates **manually** it finds the new version, just not automatically on startup.
I'm gonna update and see if the issue persists when the next version is available.

![image](https://user-images.githubusercontent.com/9649385/74829247-87b74480-5308-11ea-8387-e308b7707858.png)

**Comment by megadr01d** [comment]
> Not only that, but it's finding somehow that it's already running the current version. And the only thing I can think of is that something happened to the Sparkle framework.

Yeah, I can confirm this now. After version `k54-1219-g0f543a1b5`, the update check says I'm running the latest version when `k54-1221-g004c53962` is already released.

Gonna reopen this, maybe you can figure out what happened to Sparkle or the appcast file. Could it be a [cache issue](https://github.com/sparkle-project/Sparkle/issues/1528)?

**Comment by kode54** [comment]
It was all Sparkle's fault. They blame me and my apparent "niche" versioning. Apparently, every other user of Sparkle actually bothers to hand craft version numbers manually, rather than simply letting a script generate it.

So now everyone gets version = parent commit number. No points in the version number. The only thing that matters is "number go up", right?

**Comment by megadr01d** [comment]
Yeah, I agree. Some devs even use a script to set a date as version number, eg. `appname-20200302.zip` and I think it's fine. Version = parent commit number works just fine and besides, Sparkle is an updating framework, it should be neutral and not decide how each author should do his versioning.

**Comment by megadr01d** [comment]
Hm, It's still acting strange.

Today Cog auto checked for updates on startup just fine and found version `1113` is available. However the button to "Remind Me Later" has vanished. There's only "Skip This Version" and "Install Update". So, I closed the window because I didn't want to update just yet.
Now, it doesn't check for updates on startup anymore.

**Comment by kode54** [comment]
Report the issue to Sparkle, I didn’t make the change.

**Comment by megadr01d** [comment]
I found the [PR](https://github.com/sparkle-project/Sparkle/pull/1480) that probably introduced the bug for the "Remind Me Later" button. It should only hide the button when automatic updates are disabled, which in my case are not.

Also checked [your issue](https://github.com/sparkle-project/Sparkle/issues/1555) on Sparkle.
v1.23.0 most definitely introduced some bugs.

Anyway, you're using git commit versioning, which is only supported starting from Sparkle 1.23.0, if I understand correctly, so I'll manually update from https://kode54.net/cog, from now on. I always like to keep the latest installer so it's not too much of an hassle.

**Comment by megadr01d** [comment]
Just a heads up, I got an automatic update notice just now for version `1122`, a minute or so after launching Cog. I closed it, relaunched Cog and got no notice anymore. I guess auto updates are still working, just not on every application startup. Maybe once a day or when it feels like. Whatever.
