### ISSUE TITLE
Stream playback broken

### ISSUE THREAD

**Issue by CatGreen90** [kode54/Cog#42]
In the last 3 releases of Cog (1211-g8bc639691, 1213-g128f1ee35, and 1219-g0f543a1b5), streamed files cannot be played and are grayed out in the Add File menu:
<img width="429" alt="Screen Shot 2020-02-22 at 1 22 09 PM" src="https://user-images.githubusercontent.com/44750311/75097259-9efb6980-5576-11ea-9081-0edec7980666.png">
<img width="426" alt="Screen Shot 2020-02-22 at 1 22 59 PM" src="https://user-images.githubusercontent.com/44750311/75097262-a884d180-5576-11ea-8c9c-b60754a537b1.png">
<img width="424" alt="Screen Shot 2020-02-22 at 1 23 27 PM" src="https://user-images.githubusercontent.com/44750311/75097263-ade21c00-5576-11ea-928e-2f8aa2b05256.png">
<img width="423" alt="Screen Shot 2020-02-22 at 1 23 36 PM" src="https://user-images.githubusercontent.com/44750311/75097269-b89cb100-5576-11ea-9113-8d1aaaad9134.png">

**Comment by kode54** [comment]
I fully intended to notify you that this should be fixed. Sorry about that.
