### ISSUE TITLE
Cog hangs on loading stream

### ISSUE THREAD

**Issue by megadr01d** [kode54/Cog#43]
Cog hangs on this specific stream. Loading it in Safari plays fine.
Filetypes are supported, what could be the issue here?

https://nightride.fm/stream/nightride.m4a | https://stream.nightride.fm/nightride.m4a
https://nightride.fm/stream/nightride.mp3 | https://stream.nightride.fm/nightride.mp3
https://nightride.fm/stream/nightride.ogg | https://stream.nightride.fm/nightride.ogg

**Comment by kode54** [comment]
Unfortunately, my previous HTTP reader didn't actually support HTTPS, and would attempt to open HTTPS links as plain HTTP on port 80, and that stream would infinitely redirect them to the HTTPS link.

This much is fixed now, but I could use some help from anyone in particular with getting MP4 or CoreAudio working with user supplied file access methods. The stock CoreAudio reader only supports local files, so you can only stream the MP3 or the Ogg Vorbis streams.

**Comment by megadr01d** [comment]
> This much is fixed now, but I could use some help from anyone in particular with getting MP4 or CoreAudio working with user supplied file access methods. The stock CoreAudio reader only supports local files, so you can only stream the MP3 or the Ogg Vorbis streams.

I see. I have a preference for Ogg Vorbis anyway, and I tested it and it works now without hanging Cog. However, if I try to load the MP3 or Ogg Vorbis stream with HTTP, it doesn't redirect to HTTPS correctly, it just fails to play, giving the impression that the stream is down or not available anymore.

Doesn't `NSURLSession` do the redirection by itself?

http://stream.nightride.fm/nightride.mp3
http://stream.nightride.fm/nightride.ogg

**Comment by megadr01d** [comment]
Another example where Cog hangs is trying to open a non existent stream like:

https://nightride.fm/stream/bogus.mp3

In the browser, you get "This page isn't available", in Cog it hangs indefinitely.

**Comment by megadr01d** [comment]
Ops, I just tested it thoroughly and now it only loads HTTPS. All my other HTTP streams stopped loading with version `1115-g6d0166e69`.

**Comment by kode54** [comment]
Yeah, sorry about that. It seems NSURLSession is subject to Application Transport Security unless you explicitly allow arbitrary connections in the main Info.plist.

Also, it didn’t handle redirects or other connection issues, such as 404 errors.

**Comment by megadr01d** [comment]
> Also, it didn’t handle redirects or other connection issues, such as 404 errors.

Before anything else, thanks for improving radio streaming tremendously! Hangs and disconnects were common before version `1119`.

HTTP and HTTPS now work correctly. However, I found 4 streams that **worked on `1113` but not on `1119`**. They load up fine and apparently start playing (you see the play symbol in the gutter) but no sound is produced.

If you open them in your browser, you can see they're all from the same SHOUTcast D.N.A.S. Status server.

http://relay1.slayradio.org:8000
http://149.56.155.73:8080
http://stream-licensing.com:8056
http://209.222.19.107:8524

**Comment by kode54** [comment]
Neat, NSURLSession doesn't process the HTTP headers if it's an ICY status response, like old ShoutCast. I'll have to detect that, and process the headers myself.

**Comment by megadr01d** [comment]
Chris, I really appreciate the effort but I think this is gonna be a bit hit and miss.
More streams that worked on `1113` but not anymore.

Plays for half a second then stops

http://premium.shoutcastsolutions.com/radio/8050/256.mp3 | http://167.86.107.72:8050/256.mp3

No sound

http://ct5.fast-serv.com:9844

Hang

http://0n-80s.radionetz.de/0n-80s.mp3
http://music.myradio.com.ua:8000/Punk128.mp3
http://spoonradio.ice.infomaniak.ch/spoonradio-high.mp3

Other than that, some streams now play with sound glitches on a random basis, maybe a bug introduced with https://g.losno.co/chris/Cog/commit/25a030a46cd0f9697a2cecb38af885aab6cdd195 or https://g.losno.co/chris/Cog/commit/b37a6f0f0dbcf8d566517c2c8b57f7fe63899bb5.

I'll continue using `1113` for the time being and keep an eye on new releases.

**Comment by megadr01d** [comment]
> Neat, NSURLSession doesn't process the HTTP headers if it's an ICY status response, like old ShoutCast. I'll have to detect that, and process the headers myself.

Looks like I've fixed this, hopefully.

Forgot to add, these were fixed of course.

**Comment by kode54** [comment]
CoreAudio decoder doesn't handle streams at all. It refuses to, because Apple has their heads up their asses.

The only decoders that handle streams properly are my decoders, namely Ogg Vorbis, Ogg Opus, and the MP3 decoder in the FFmpeg component.

**Comment by megadr01d** [comment]
> CoreAudio decoder doesn't handle streams at all. It refuses to, because Apple has their heads up their asses.

Do agree.

> Do note that I'm not rolling back to the ancient do-the-entire-http-exchange-ourselves-with-low-level-sockets method. So go ahead and stay on 1113 forever.

Not asking you to. New method is superior. Old one disconnects a lot.
Just wondering why old streams got broken, that's all.
But I get your tone, so thanks for fixing all the endless redirects, HTTPS and ICY header streams, Chris.

Cheers.

**Comment by megadr01d** [comment]
Hey my friend, I have good news.

Regarding the [latest broken streams](https://github.com/kode54/Cog/issues/43#issuecomment-597365707), I was too tired the last time, but today I got my head around it and was able to fix them by either:

- removing the `.mp3` extension
- remove the last part after the port or tld, eg. `/256.mp3`, `/0n-80s.mp3`, `/relay.mp3`, etc.
- replacing `.mp3` with `.ogg` [on streams that supported both formats]

I guess it has some trouble with the `mp3` extension (my local music collection is all Ogg Vorbis encoded).

Except for http://ct5.fast-serv.com:9844 [rare 80s music], which I'm still trying to get around by trial and error, I was able to fix them all so, thanks to you and your coding skills, I'm now enjoying the latest version `1122` in all its glory. No more hangs or disconnects.

Just wanted to share this with you, Chris. Cheers.

**Comment by megadr01d** [comment]
Alas, some streams can't be "fixed". Streams that end on `.mp3` were seriously broken (they hang Cog or play with sound glitches).

**Comment by kode54** [comment]
I suppose I can revert this entire commit series and simply disable the nonexistent https support. Who needs https anyway?

**Comment by megadr01d** [comment]
Well, I have to agree. This issue is about Cog hanging and no one likes having to force quit an app over and over again. Something feels wrong about an app hanging. And the fact of the matter is that it still hangs after those commits, just on different streams.

I'd prefer if Cog just drops the connection and stops playback attempt if a stream is not supported such as

- an unsupported file format (like AAC/AACPlus: audio/aacp)
- an https connection
- an old unsupported ShoutCAST server version

Out of sight out of mind, if Cog doesn't play a specific stream, I'll just trash it and search for a new one, simple. But hanging the app, just makes me keep thinking.

**Comment by megadr01d** [comment]
Added a few other conditions to the list above, like not found, forbidden, busy streams..

**Comment by megadr01d** [comment]
Version `1134-g798cc4ce4` seems to be pretty stable at the moment so thanks for the update, Chris.

Another thing that I wasn't paying attention to, and one more reason for Cog to disconnect an unsupported/unavailable stream instead of keeping trying to connect to it, is that I keep **Repeat > All** enabled when I listen to radio streams. That way, if a stream drops the connection (user overload, buffer issues or even my own internet ISP being a jerk), Cog just keeps retrying the next stream and looping the playlist so I'm never out of music.
