### ISSUE TITLE
Tabs

### ISSUE THREAD

**Issue by ellul-ezra** [kode54/Cog#44]
This is a question (or two) not an issue: It's possible to display a tab bar and there is a greyed out 'show all tabs' item in the view menu, but I see no way of creating tabs; has this functionality been removed or is it planned for a future release? And can playlists be saved and/or imported/exported (perhaps to a separate tab!)??

**Comment by megadr01d** [comment]
Cog never supported tabs. "Show all tabs" must be a newer macOS thing and it's not present in OS X 10.11. Can you please post a screenshot?

Playlists can be saved in **File > Save as**. It saves all playlist items as full paths, you just need to provide a `.m3u` extension. To import, just use **File > Add File** or open from your favorite launcher.

**Comment by ellul-ezra** [comment]
Ah ok, I see. Yes, I'm on Catalina.

<img width="813" alt="Screenshot 2020-03-07 at 17 34 35" src="https://user-images.githubusercontent.com/19375781/76148080-b1a78f80-609a-11ea-9f71-74dc74aa5270.png">

Regarding playlists, as I ordinarily have the file tree and spotlight exposed I did not explore the 'file' menu options very well. My apologies.

**Comment by megadr01d** [comment]
What if you select "Show Tab Bar"? In the File menu do you see "Open New Tab"?
I know that even in 10.11 El Capitan, if you use Mail.app in Full Screen, selecting "File > New Message" opens new messages in tabs, not windows. Finder.app also supports tabs (doesn't have to be Full Screen) in El Capitan.

Regarding playlists, just save them in the File menu and load them in the folder you saved them using Cog's file tree.

**Comment by ellul-ezra** [comment]
A pity but no, I had fiddled around with showing the tab bar previously and no menu options are available. 

<img width="279" alt="Screenshot 2020-03-08 at 00 11 51" src="https://user-images.githubusercontent.com/19375781/76154333-89d41e00-60d2-11ea-80cd-6e63abc07a6c.png">
<img width="300" alt="Screenshot 2020-03-08 at 00 12 05" src="https://user-images.githubusercontent.com/19375781/76154335-8e003b80-60d2-11ea-94d1-2fd4cb184b24.png">

My experience is of non-Gnome Linux applications so I was expecting playlist functions to be available on the interface or from context clicks. The file menu and tree is just fine :) Thanks for the responses.

**Comment by kode54** [comment]
If you must have multiple playlists, try [foobar2000 for Mac](https://www.foobar2000.org/mac). It has working tag editing, and ReplayGain scanning, too.

**Comment by ellul-ezra** [comment]
Multiple playlists aren't a must but been keeping an eye on that project anyway. I've used some of your pc foobar plugins in the past so thanks for that!

**Comment by megadr01d** [comment]
> The file menu and tree is just fine :) Thanks for the responses.

You're welcome, @ellul-ezra. Don't forget to close the issue if solved.
