### ISSUE TITLE
HEAD is referencing unavailable mGBA commit

### ISSUE THREAD

**Issue by JanX2** [kode54/Cog#50]
Any chance you could push to https://g.losno.co/chris/mgba.git?

Thanks! :)

**Comment by kode54** [comment]
Master refers to commit 93cb7b0dc8aab92d1b88604609acaf971cb3c5e0, which is in the repo.

The experimental branch on my repository points to 523515c16efd5d4abb8aaebdb124fdc38d3aa071, which is also in the repo.

**Comment by JanX2** [comment]
The issue was that the URL changed from github to https://g.losno.co/chris/mgba.git. For some reason `git submodule update --init --recursive` does not take care of that. I had to manually change it using `git remote set-url origin https://g.losno.co/chris/mgba.git` from within the mgba directory. Then rerun `git submodule update --init --recursive`.

**Comment by kode54** [comment]
Changes to submodules require running `git submodule sync`.

**Comment by JanX2** [comment]
Ah. Thanks. Either I had forgotten or this has changed at some point!
