### ISSUE TITLE
Media Key

### ISSUE THREAD

**Issue by poxin13** [kode54/Cog#51]
Media keys only seem to work when this is the only thing open playing media. Example is if VLC and Cog are open, the media keys will only work in VLC. Likewise if Cog is not playing a track (but is open), the play button will open Apple Music instead of  resuming.

**Comment by kode54** [comment]
Media Keys on 10.14 and newer use a system API for Media Key events, and properly take control depending on playing a file, or the app receiving focus. Apps will still fight over media key focus, and there's nothing I can do about this. Apple made it even less possible to hook system events globally with 10.14, and outright impossible with 10.15. I'm not continuing development of new features for anything older, unless the new features just happen to work on my older targets.
