### ISSUE TITLE
No icons in tolbar

### ISSUE THREAD

**Issue by dud0n** [kode54/Cog#55]
No icons in tolbar after last update cog Version 1161 (1161-g55ebd62eb)
macos 10.13.6 (17G14019)

![Screen Shot 2020-11-19 at 20 38 43](https://user-images.githubusercontent.com/41061134/99702963-91442780-2aa7-11eb-85d3-7a635c21ff4d.png)

**Comment by iparr** [comment]
I have the same problem with the same version, but on MacOS 10.14.3

![Screenshot 2020-11-19 at 23 02 17](https://user-images.githubusercontent.com/497635/99734811-5b10a300-2abb-11eb-9acc-3353abf0a973.png)

**Comment by kode54** [comment]
This is sort of embarrassing for both me, and for my co-developer, who was working on the icon replacements using SF Symbol. Unfortunately, in my rush to get a Universal build out, I forgot that the icon replacement process was incomplete. Currently, the symbols only work on Big Sur. :[

I'll push a release soon that fixes this, so in the mean time, you can continue using the previous release.

**Comment by kode54** [comment]
This should be fixed with the latest release.

**Comment by kode54** [comment]
Okay, it looks like I actually need to test things on 10.15 and older, which is a pain, since I can't dual boot that. I guess I'll look into testing this later. For now, the updates are marked for 11.0 only now, so nobody automatically gets them.

**Comment by iparr** [comment]
Aye, the update (Version 1163-gdca9655c6) removes the one working button I had.

![Screenshot 2020-11-20 at 15 55 10](https://user-images.githubusercontent.com/497635/99820546-d79d9300-2b48-11eb-934c-6b3f263cb201.png)

Also, "Check for updates" is now greyed out and inactive. I don't know if that's a related issue.

**Comment by waaykool** [comment]
Same problem here, using versions 1161 & 1163 in Mojave 10.14.6 breaks button icons.

**Comment by kode54** [comment]
This has been fixed for a while now, by reverting the attempt to use the SF Symbol buttons to the original icon resources. Apparently, it's not really even feasible to use SF Symbol in anything less than Big Sur without rendering everything to PDFs like are already being used for the current vector objects.
