### ISSUE TITLE
Since version 1161 does not open on 10.11

### ISSUE THREAD

**Issue by MacTerrassa** [kode54/Cog#57]
The last version that opens without problem is 1148, it seems that not only support for 10.8 has ended but several later versions, or at least mine for 10.11.
From version 1161, trying to open it starts the boot but closes again immediately before seeing any windows, and I get an alert, with the message copied below from the console:
"rashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

VM Regions Near 0:
--> 
    __TEXT                 000000010dc3f000-000000010dc7b000 [  240K] r-x/r-x SM=COW  /Users/USER/Downloads/Cog.app/Contents/MacOS/Cog

Application Specific Information:
/Users/joseluis/Downloads/Cog.app/Contents/PlugIns/MIDI.bundle/Contents/MacOS/libbassmidi.dylib
"

**Comment by kode54** [comment]
I guess this confirms that I need to mark all releases from now on as requiring 10.13 or newer.

**Comment by MacTerrassa** [comment]
Obviously, I would like it to keep support for my system (and previous ones) :-)
But if it is not possible, the logical thing is to mark your actual requirements currently as it has changed on your website already. It is always appreciated that these details are clear, especially so that users know correctly whether or not they can install a program or an update. Thank you.
Regards
Jose Luis

**Comment by kode54** [comment]
Yes, I would like to support as low as possible, which this SDK allows, 10.9. Unfortunately, there seems to be an issue with dependencies. I may need to bug Ian Luck about BASS and company, since those are the only ones I don't control the builds for.
