### ISSUE TITLE
A few nulls in notification centre :)

### ISSUE THREAD

**Issue by fgimian** [kode54/Cog#8]
Hello there, thanks so much for continuing work on Cog, I've been using it for years and love it 😄 

I noticed a little issue in Notification Centre with the latest k54 version:

![screen shot 2018-06-04 at 11 18 37 am](https://user-images.githubusercontent.com/1811813/40893953-2d480f22-67e9-11e8-9fdb-c6ef1125b403.png)

Notice the nulls there.

This particular tune has no tags, so perhaps that information should be excluded when it's not available?

Cheers
Fotis

**Comment by kode54** [comment]
This should be fixed in the latest release.

**Comment by fgimian** [comment]
Thanks a lo! 😄

**Comment by fgimian** [comment]
Just tested and can confirm this bug is fixed in the latest release, closing 💃
