### ISSUE TITLE
New pull #88 breaks many file inputs

### ISSUE THREAD

**Issue by kode54** [kode54/Cog#89]
The code which now converts stringified paths into NSURLs now turns the colons after the scheme specifier into `%3A`, thus forming relative URLs with no valid scheme. What's the best way to fix this?

**Comment by kode54** [comment]
Looks like someone already found us a solution, I've implemented it and it appears to work.

https://developer.apple.com/forums/thread/6899

**Comment by nevack** [comment]
Oh, sorry. I thought this was just a mechanical conversion from deprecated method to proposed one.

**Comment by kode54** [comment]
Unfortunately, the new method is designed for safely encoding URL components, but not complete URLs.
